config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :recipes

  resources :users, only: [:edit, :update]

  resources :user_recipes, only: [:index, :create, :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :user, dependent: :destroy

  def self.countries
    [
      "US",
      "CA",
    ]
  end

  def self.currencies
    [
      "USD",
      "CAD",
    ]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true

  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :author, presence: true

  has_many :recipe_categories
  has_many :categories, through: :recipe_categories

  has_many :user_recipes
  has_many :recipes, through: :user_recipes

  before_save { generate_test_ingredients if Rails.env.test? }

  def self.find_random
    order('RANDOM()').first
  end

  def generate_test_ingredients
    ingredients = []
    rand(10).times do
      ingredients.push(Faker::Food.ingredient)
    end
    self.ingredients = ingredients.join(', ')
  end
end

app/models/recipe_category.rb
# frozen_string_literal: true

class RecipeCategory < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :user_recipes
  has_many :recipes, through: :user_recipes, dependent: :destroy

  after_create_commit :create_user_address

  def name_or_email
    if current_address.first_name.present?
      current_address.first_name
    else
      email
    end
  end

  def current_address
    addresses.order(:created_at).last
  end

  def admin?
    admin == true
  end

  protected

  def create_user_address
    addresses.create!
  end
end

app/models/user_recipe.rb
# frozen_string_literal: true

class UserRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @amount = 100

    customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Test Customer Charge',
        currency: 'usd'
    )

    rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_charge_path
  end
end

app/controllers/concerns/loggable.rb
module Loggable
  extend ActiveSupport::Concern

  def log_create_recipe(success, user = nil, recipe = nil)
    if success.present?
      Rails.logger.info "Created recipe with recipe_id=#{recipe.id}"
    else
      Rails.logger.error "Unable to create recipe for user=#{user.id}"
    end
  end

  def log_create_user_recipe(success, user = nil, recipe = nil)
    if success.present?
      Rails.logger.info "Created user_recipe with user_id=#{user.id}, recipe_id=#{recipe.id}"
    else
      Rails.logger.error "Unable to create user_recipe for user=#{user.id}"
    end
  end

  def log_destroy_user_recipe(success, user = nil, recipe = nil)
    if success.present?
      Rails.logger.info "Destroyed user_recipe with user_id=#{user.id}, recipe_id=#{recipe.id}"
    else
      Rails.logger.error "Unable to destroy user_recipe for user=#{user.id}"
    end
  end

  def log_edit_user_address(user)
    Rails.logger.error "Unable to update user address for user=#{user.id}"
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @recipe = Recipe.find_random
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :authenticate_user!

  include Loggable

  def show
    @recipe = Recipe.find(show_params[:id])
    @random_recipe = Recipe.find_random
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.new(create_params)

    if recipe.save
      current_user.recipes << recipe
      log_create_recipe(:success, current_user, recipe)
      flash[:notice] = "#{recipe.name} was successfully created"

      redirect_to user_recipes_path
    else
      log_create_recipe(nil, current_user)
      flash[:error] = "Recipe not created, please try again"

      render :new
    end
  end

  private

  def create_params
    params
      .require(:recipe)
      .permit(:name, :serves, :prep_time, :cooking_time,
              :ingredients, :instructions, :author)
  end

  def show_params
    params.permit(:id)
  end
end

app/controllers/user_recipes_controller.rb
# frozen_string_literal: true

class UserRecipesController < ApplicationController
  before_action :authenticate_user!

  include Loggable

  def index
    @recipes = current_user.recipes
  end

  def create
    recipe = Recipe.find get_recipe_id
    user_recipe = UserRecipe.new({
      recipe_id: recipe.id,
      user_id: current_user.id,
    })

    if user_recipe.save
      flash[:notice] = "Added #{recipe.name} to your Recipes!"
      log_create_user_recipe(:success, current_user, recipe)

      redirect_to recipe_path(recipe.id)
    else
      flash[:error] = "Recipe not added, please try again"
      log_create_user_recipe(nil, current_user)

      redirect_to recipe_path(recipe.id)
    end
  end

  def destroy
    recipe = Recipe.find get_recipe_id
    user_recipes = current_user.user_recipes.where(recipe_id: recipe.id)

    user_recipes.destroy_all
    flash[:notice] = "Removed #{recipe.name} from your Recipes!"
    log_destroy_user_recipe(:success, current_user, recipe)

    redirect_to user_recipes_path
  rescue
    flash[:error] = "Unable to remove Recipe, please try again"
    log_destroy_user_recipe(nil, current_user)

    redirect_to user_recipes_path
  end

  private

  def get_recipe_id
    params.permit(:recipe_id).dig(:recipe_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  include Loggable

  def edit
    @user = current_user
    @address = @user.current_address
  end

  def update
    current_user.current_address.update(address_params)

    flash[:notice] = "Preferences updated successfully"

    redirect_to edit_user_path
  rescue
    log_edit_user_address(current_user)
    flash[:error] = "Unable to update preferences"

    render :edit
  end

  private

  def address_params
    params.require(:user).permit(:first_name, :last_name, :line1, :line2, :city, :state, :postal_code, :country, :currency)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.haml
%h1= "Welcome to Recipe Roulette"

- if current_user
    #{ button_to 'Find a random Recipe!', recipe_path(@recipe.id), method: :get }
- else
- if current_user && current_user.admin?
    #{ link_to 'Admin Dashboard', rails_admin.dashboard_path }

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, msg| %>
    <div>
        <%= msg %>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, msg|
  - if type == "notice"
    %div{ class: "alert alert-primary" }= msg
  - elsif type == "error"
    %div{ class: "alert alert-danger" }= msg

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeRouletteRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <div class="container">
      <div class="row">
          <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <%= link_to "Recipe Roulette", root_path, method: :get, class: "btn border" %>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <%# add items %>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Options
                    </a>
                    <ul class="dropdown-menu">
                      <% if current_user %>
                        <li>
                          <%= link_to "Add Recipe", new_recipe_path, class: "dropdown-item" %>
                        </li>
                        <li>
                          <%= link_to "My Recipes", user_recipes_path, class: "dropdown-item" %>
                        </li>
                        <li>
                          <%= link_to "Preferences", edit_user_path(current_user), class: "dropdown-item" %>
                        </li>
                        <li>
                          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                        </li>
                      <% else %>
                        <li>
                          <%= link_to 'Sign Up', new_user_registration_path, class: "dropdown-item" %>
                        </li>
                        <li>
                          <%= link_to 'Sign In', new_user_session_path, class: "dropdown-item" %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>

        <%= render 'layouts/flash_messages' %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/recipes/new.html.haml
%h1 Create a new Recipe!

= form_with model: @recipe do |form|
  = form.text_field :name, placeholder: "Enter recipe name"
  %br
  = form.text_field :serves, placeholder: "Serves how many?"
  %br
  = form.text_field :prep_time, placeholder: "What is the prep time?"
  %br
  = form.text_field :cooking_time, placeholder: "What is the cooking time?"
  %br
  = form.text_area :ingredients, size: "23x10", placeholder: "What are the ingredients?"
  %br
  = form.text_area :instructions, size: "23x10", placeholder: "How do I make it?"
  %br
  = form.text_field :author, placeholder: "Enter author name"
  %br
  = form.submit "Submit"

app/views/recipes/show.html.haml
%h1= @recipe.name

%br
Serves:
%strong= @recipe.serves
%br
Prep Time:
%strong= @recipe.prep_time
%br
Cooking Time:
%strong= @recipe.cooking_time
%br
Ingredients:
%strong= @recipe.ingredients
%br
Instructions:
%strong= @recipe.instructions
%br
Author:
%strong= @recipe.author

%br

#{ button_to 'Find a random Recipe!', recipe_path(@random_recipe.id), method: :get }

%br

#{ button_to 'Save Recipe', user_recipes_path, params: { recipe_id: @recipe.id } }

app/views/user_recipes/_recipes.html.haml
%ul
  - current_user.recipes.each do |recipe|
    %li= link_to recipe.name, recipe_path(recipe.id)
    = button_to "-", user_recipe_path(recipe.id), method: :delete, params: { recipe_id: recipe.id }, class: "btn btn-secondary btn-sm"

app/views/user_recipes/index.html.haml
%h1= "Saved Recipes for #{current_user.name_or_email}"

= render "recipes"

app/views/users/_edit_form.html.haml
= form_with model: @user do |form|
  %br
  %p= "First Name"
  = form.text_field :first_name, value: @address.first_name, autofocus: true
  %br
  %p= "Last Name"
  = form.text_field :last_name, value: @address.last_name
  %br
  %p= "Address Line 1"
  = form.text_field :line1, value: @address.line1
  %br
  %p= "Address Line 2"
  = form.text_field :line2, value: @address.line2
  %br
  %p= "City"
  = form.text_field :city, value: @address.city
  %br
  %p= "State"
  = form.text_field :state, value: @address.state
  %br
  %p= "Postal Code"
  = form.text_field :postal_code, value: @address.postal_code
  %br
  %p= "Country"
  = form.select :country, Address.countries, selected: @address.country
  %br
  %p= "Currency"
  = form.select :currency, Address.currencies, selected: @address.currency
  %br
  = form.submit "Submit"

app/views/users/edit.html.haml
%h1 Update your preferences

= render "edit_form"